### ISSUE TITLE
Missing response header X-Amz-Function-Error

### ISSUE THREAD

**Issue by jscheid** [aws/aws-lambda-runtime-interface-emulator#20]
I wasn't sure whether to open this here or over in https://github.com/aws/aws-lambda-nodejs-runtime-interface-client

With a simple example that always throws an error:

```Dockerfile
FROM public.ecr.aws/lambda/nodejs:12
RUN echo 'module.exports = { handler: () => { throw new Error("failure"); } }' > index.js
CMD ["index.handler"]
```

When I hit the endpoint:
```
$ curl -qv http://localhost:8080/2015-03-31/functions/function/invocations -d '{}'
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
> POST /2015-03-31/functions/function/invocations HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.64.1
> Accept: */*
> Content-Length: 2
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 2 out of 2 bytes
< HTTP/1.1 200 OK
< Date: Mon, 18 Jan 2021 23:27:37 GMT
< Content-Length: 184
< Content-Type: text/plain; charset=utf-8
< 
* Connection #0 to host localhost left intact
{"errorType":"Error","errorMessage":"failure","trace":["Error: failure","    at Runtime.handler (/var/task/index.js:1:43)","    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"]}* Closing connection 0
$
```

As expected, the response payload has the shape described in https://docs.aws.amazon.com/lambda/latest/dg/nodejs-exceptions.html and the status is 200 to denote a function error.

However, shouldn't the response headers include `X-Amz-Function-Error` so that the error status can be determined without relying on heuristics?

**Comment by mglickVA** [comment]
I agree with the post above.  I have been trying to test container based lambda with aws-stepfunctions-local and I believe the aws-stepfunctions-local doesn't recognized that the Lambda executed in error as the header is missing.

**Comment by jove4015** [comment]
+1 asking for someone to please fix this.  We need this header to come back in order for stepFunctions to detect that there is an error.  This is making it just about impossible to test our error flow.  Since now, we have to give direct AWS access to anyone to have their own copy of the lambda in order to work on it, the whole step functions local functionality is just useless.  We can't rely on it for local development, only because of this one header missing in the runtime emulator.

What's even worse, you can't see the source code for step functions local anymore, so the only way to figure this out is by trial and error.  It has wasted hours and hours of my time today trying to figure out why my stepfunctions don't fail after all this time working out the right state machine language.  These things are hard enough to do when the local development tools you're given work properly; it's much worse when those tools lead you chasing completely unexplainable behavior for hours while you just guess at what might be wrong.

It's been a year and a half.  Please, add the header already.

**Comment by jsommr** [comment]
+1
