### ISSUE TITLE
Runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by tcmbilozub** [aws/aws-lambda-runtime-interface-emulator#97]
After the latest changes the following error occurs when executing several simultaneous requests:

----
19 Jun 2023 22:05:39,909 [INFO] (rapid) ReserveFailed: AlreadyReserved
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x68c30f]

goroutine 131 [running]:
go.amzn.com/lambda/rapidcore.(*Server).Invoke.func2()
	/LambdaRuntimeLocal/lambda/rapidcore/server.go:653 +0xef
created by go.amzn.com/lambda/rapidcore.(*Server).Invoke
	/LambdaRuntimeLocal/lambda/rapidcore/server.go:636 +0x23d

----

Docker image: public.ecr.aws/lambda/python:3.8

**Comment by nparker2020** [comment]
Hey @tcmbilozub 
I ran into this same issue and it turned out to be an incorrect path to the python executable that was passed to the runtime interface emulator. Posting here to hopefully help others.
```

Starting mock Lambda runtime:
16 Aug 2023 16:42:49,811 [INFO] (rapid) exec '/usr/bin/python' (cwd=/, handler=awslambdaric)
16 Aug 2023 16:42:51,574 [INFO] (rapid) extensionsDisabledByLayer(/opt/disable-extensions-jwigqn8j) -> stat /opt/disable-extensions-jwigqn8j: no such file or directory
16 Aug 2023 16:42:51,574 [INFO] (rapid) Configuring and starting Operator Domain
16 Aug 2023 16:42:51,574 [INFO] (rapid) Starting runtime domain
16 Aug 2023 16:42:51,574 [WARNING] (rapid) Cannot list external agents error=open /opt/extensions: no such file or directory
16 Aug 2023 16:42:51,574 [INFO] (rapid) Starting runtime without AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_SESSION_TOKEN , Expected?: false
START RequestId: e4769e06-19d6-45c7-969f-a310d8769df9 Version: $LATEST
16 Aug 2023 16:42:51,574 [WARNING] (rapid) First fatal error stored in appctx: Runtime.InvalidEntrypoint
******************************************************************************************************************************************
16 Aug 2023 16:42:51,574 [ERROR] (rapid) Init failed InvokeID= error=fork/exec /usr/bin/python: no such file or directory
******************************************************************************************************************************************

16 Aug 2023 16:42:51,574 [INFO] (rapid) Starting runtime domain
16 Aug 2023 16:42:51,574 [WARNING] (rapid) Cannot list external agents error=open /opt/extensions: no such file or directory
16 Aug 2023 16:42:51,575 [INFO] (rapid) Starting runtime without AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_SESSION_TOKEN , Expected?: false
16 Aug 2023 16:42:51,575 [WARNING] (rapid) Omitting fatal error Runtime.InvalidEntrypoint: Runtime.InvalidEntrypoint already stored
START RequestId: 9098b9f6-2ec1-4574-976c-c1f708284870 Version: $LATEST
16 Aug 2023 16:42:55,910 [INFO] (rapid) ReserveFailed: AlreadyReserved
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x699b8f]

goroutine 51 [running]:
go.amzn.com/lambda/rapidcore.(*Server).Invoke.func2()
        /LambdaRuntimeLocal/lambda/rapidcore/server.go:653 +0xef
created by go.amzn.com/lambda/rapidcore.(*Server).Invoke
        /LambdaRuntimeLocal/lambda/rapidcore/server.go:636 +0x23d
```

**Comment by tcmbilozub** [comment]
Temporarily solved this problem by downgrading to a lower version.

`RUN curl -Lo /usr/local/bin/aws-lambda-rie https://github.com/aws/aws-lambda-runtime-interface-emulator/releases/download/v1.10/aws-lambda-rie \
  && chmod +x /usr/local/bin/aws-lambda-rie`

**Comment by benoit-laplante** [comment]
Having same issue with simultaneous requests under python 3.8
```
(rapid) ReserveFailed: AlreadyReserved
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x699b8f]
goroutine 45 [running]:
go.amzn.com/lambda/rapidcore.(*Server).Invoke.func2()
     /LambdaRuntimeLocal/lambda/rapidcore/server.go:653 +0xef
 created by go.amzn.com/lambda/rapidcore.(*Server).Invoke
     /LambdaRuntimeLocal/lambda/rapidcore/server.go:636 +0x23d
```

**Comment by achernyakov-rvbd** [comment]
I too am hitting this when making simultaneous requests. Is there any workaround other than downgrading to an old version?

**Comment by fs-aikito** [comment]
The offending code is here

https://github.com/aws/aws-lambda-runtime-interface-emulator/blob/develop/lambda/rapidcore/server.go#L661-L666

It checks if `Reserve()` fails and logs message but then continues on as if nothing was wrong while `reserveResp` is `nil` causing this segfault immediatly when trying to access `reserveResp.Token`

**Comment by jmehnle** [comment]
The permanent link for this code section is: https://github.com/aws/aws-lambda-runtime-interface-emulator/blob/d37e08c13600eae4deb1329603f01a78363f360e/lambda/rapidcore/server.go#L661-L666. I looked at this code, and I'm not sure as to what a good fix might be. One possibility would be to pull the `s.Reserve()` call out of the `go func` into the main `Invoke()` body, which would make the `s.Reserve()` call synchronous, allowing us to return from `Invoke()` with an error. This appears to be roughly [what the previous version of `Invoke()` did](https://github.com/aws/aws-lambda-runtime-interface-emulator/blob/c1cf0c518004962baa79bd82d5c4c2776e15073f%5E/lambda/rapidcore/server.go#L577-L593), but it seems undoing that would contravene the intent behind moving the `s.Reserve()` call into an asynchronous goroutine.

AWS, can someone please comment on what your plans are for addressing this regression?

**Comment by jperezr21** [comment]
Any updates on this? Makes testing locally impossible for some use cases.

**Comment by myedibleenso** [comment]
> Temporarily solved this problem by downgrading to a lower version.
> 
> `RUN curl -Lo /usr/local/bin/aws-lambda-rie https://github.com/aws/aws-lambda-runtime-interface-emulator/releases/download/v1.10/aws-lambda-rie \ && chmod +x /usr/local/bin/aws-lambda-rie`

Thank you, @tcmbilozub , for this workaround.   With the earlier version you identified at least the first request made can complete (tested with python 3.11).

Given its effect on concurrency and the popularity of lambda, I'm surprised this regression hasn't garnered more attention by now.  Someone once said "speed matters in business."  AWS lambda team, please consider prioritizing this for your customers.

**Comment by OJFord** [comment]
As alluded to above, downgrading isn't really a solution, since it'll still error '[INFO] (rapid) ReserveFailed: AlreadyReserved', it just won't panic on it.

The issue seems to be that `Reserve` tries to update the single context, on the single `Server`, and so it just inherently can't serve multiple concurrent invocations:
https://github.com/aws/aws-lambda-runtime-interface-emulator/blob/71388dd788b7a5519262391ce73fe6548dbaf86e/lambda/rapidcore/server.go#L159-L199

but I'm not that familiar with Go, nevermind this project, and I don't know the solution.

Are you able to comment @valerena?

**Comment by OJFord** [comment]
I believe I have a fix/workaround (?) in #133.

**Comment by valerena** [comment]
The situation here is that for requests running in the Lambda service in the cloud, there will never be concurrent requests, because Lambda manages concurrent requests in different sandboxes/environments that don't interact with each other (therefore different instances of the Lambda Runtime API). This emulator package is a close representation of what's actually executed in the real Lambda hosts, and that's why the concurrent use case is not supported here either.

About the proposed fix, it's modifying behavior that is coming from that internal functionality, and we try to not have deviations on that side. 

We will analyze it a bit more, to see if we can come up with a solution that works well for the local invocations, but without affecting the actual execution in the real Lambda environments.

**Comment by jmehnle** [comment]
@valerena, I think it would be very much acceptable for the RIE to not concurrently handle requests (however that would manifest), although that would certainly be nice to have. The most important feature would be for the RIE to not crash.

**Comment by HWiese1980** [comment]
What is the status here? I'm experiencing this issue in a custom docker image run locally where my base image is "public.ecr.aws/lambda/python:3.12.2024.10.30.16-x86_64" (for example). Can this be mitigated?

**Comment by OJFord** [comment]
@HWiese1980 We're still using the workaround I shared above, it does work, but I completely understand @valerena's point that it's hacking up the upstream/internal behaviour rather than adding to/harnessing it in some way as the emulator project intends. To do that though, as I understand, you'd need some kind of 'supervisor', a Lambda _API_ emulator, to launch either multiple containers or multiple runtime interface emulator processes within a container.

Essentially the problem is that the container is an [execution environment](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtime-environment.html); mirroring Lambda is a feature; what's missing is spawning multiple execution environments in a way that mirrors the service & VM management part of Lambda.

**Comment by four43** [comment]
Why should the RIE handle concurrent requests? If it's meant to truly emulate the Lambda service it should really only handle one at a time. Can the socket just block until the request is done?

**Comment by OJFord** [comment]
@four43 Yes, see my comment above; the issue arises because people use this for their container image, then run that same image in local development - say, in docker compose - and it's identical to when it runs in production Lambda except it segfaults on multiple requests: there's nothing sitting in front spinning up multiple instances of the RIE in response to multiple concurrent requests.

**Comment by four43** [comment]
Only because they didn't do it?Running concurrently is actually a huge negative, not a positive. I'm not expecting locking issues and race conditions in lambda! Reading and writing local files now need  m semaphores. If all of a sudden I have those because it's running multiple requests at once, that's a disaster. If you want concurrency, spin up multiple containers. That's outside of the scope of this project. That's orchestration. Those concerns are very separate.

**Comment by OJFord** [comment]
Yes that's what I've described passim.

The issue arises because the project is suggested and used as a local imitation of Lambda - you can run the same image as you deploy - but then the missing piece is that orchestration or API/service/VM management emulation.

**Comment by four43** [comment]
Maybe the better solution is to update the docs to show a docker example with multiple functions running in docker then?

**Comment by wisnij** [comment]
I ran into this issue recently, and even after finding this thread I was a bit confused because my test environment was only using lambdas serially, with no concurrent requests intended at all. Ultimately the issue turned out to be that I'm running the lambda container as one service in a Docker Compose file, and its healthcheck command works by sending an empty event to the container with curl as described in this repo's README. So there's a race condition where, if the healthcheck happens to send its own request to the lambda container at the same time as an actual test request, the container will crash due to the concurrent requests. This manifests to the user as seemingly random test flakes.

For now my workaround is to set the healthcheck interval to longer than the tests typically take to complete, effectively disabling it for the duration. This kinda works but is brittle – if we later added more tests, for example, they might need more time to complete and could run into a concurrent request again.

I am not well-versed in the code here, so this may not be a feasible solution, but could the emulator not simply fork off a child process to handle each incoming request, to avoid any in-process concurrency issues? Barring that, restricting it to only process a single request at a time as @four43 suggests above would also be acceptable, if that's all it can handle without panicking.

**Comment by OJFord** [comment]
We've been using the workaround PR I shared above (https://github.com/aws/aws-lambda-runtime-interface-emulator/issues/97#issuecomment-2362172477) in local development for more than six months, no issue, in exactly that kind of docker compose setup.

As I've said above though it's not really appropriate for merging, since the issue remains that in a real deployed Lambda this _is_ invoked singly, it's not the 'service' level orchestrator that we're using it as in compose.

(There's localstack which offers that, but it's pretty heavyweight and then you have to buy in to registering your lambdas with it somehow which can't necessarily tie up with how you do that in production anyway, so then what are you really achieving.)

**Comment by HWiese1980** [comment]
Just my two cents... I took another road now, ditching the enveloping docker container entirely and calling the handler directly with a fake Lambda context. Works like a charm for me and also allows me to debug into the handler. I see no reason why I should not do it this way. The webserver.py that I am using sufficiently "simulates" the load balancer for my needs and even has some of the limitations and quotas of the load balancer in place (e.g., response length not longer than 1 megabyte).

**Comment by Sillocan** [comment]
Does the new LMI interface support concurrent execution?
